# Generated by Django 4.0.5 on 2022-08-03 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
